# Generated by Django 4.2.2 on 2023-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_alter_game_is_waiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
